# Site settings
title: Ascend Project
email: info@ascendproject.org
description: "Mentorship and barrier-removing accelerator program designed to explicitly invite, include, and support adult learners in making a first technical contribution to Open Source software."
baseurl: ""
url: "http://ascendproject.org"
homeurl: "/about/"
github: "http://github.com/mozilla/ascendproject"

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
navigation:
- title: About
  url: /about/index.html
- title: Blog
  url: /index.html
- title: Application Form
  url: /apply/index.html
- title: Participants
  url: /application/index.html
- title: Volunteers
  url: /volunteers/index.html
#- title: Press
#  url: /press/index.html
