# Site settings
title: Ascend Project
email: info@ascendproject.org
description: "Mentorship and barrier-removing accelerator program designed to explicitly invite, include, and support adult learners in making a first technical contribution to Open Source software."
baseurl: ""
url: "http://ascendproject.org"
homeurl: "/about/"
github: "http://github.com/mozilla/ascendproject"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
permalink: pretty

# Navigation
navigation:
- title: About
  url: /about/index.html
- title: Blog
  url: /index.html
- title: Portland Ascend
  url: /participants/portland/index.html
- title: Course Materials
  url: /course_materials
- title: Volunteers
  url: /volunteers/index.html
- title: FAQ
  url: /faq/index.html

# Links we don't need right now
#- title: Apply
#	url: /apply/index.html
#- title: Info For Participants
#	url: /application/index.html
